name: CI for Pytest
on: push

jobs:
  pytest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Upgrade to Python 3
        uses: cclauss/Upgrade-to-Python3@0.1.0
      
      - name: Install pytest
        run: pip3 install pytest jinja2 boto3
      - name: test with pytest
        run: pytest tests/test_mypackage.py -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


